title: QZTZ Base Metal Research
description: Daily Charts Updates!
theme: just-the-docs
search_enabled: False
heading_anchors: true
back_to_top: true
back_to_top_text: "Back to top"
baseurl: "/your-repo" # 如果网站地址是 username.github.io/your-repo

url: https://just-the-docs.github.io

aux_links:
  返回首页: https://yingfengwu-cn.github.io/qztz/
