title: QZTZ Base Metal Research
description: Daily Charts Updates!
theme: just-the-docs
search_enabled: False
heading_anchors: true

url: https://just-the-docs.github.io

aux_links:
  返回首页: https://yingfengwu-cn.github.io/qztz/
